# builder stage
FROM node:20 AS builder
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .

# production stage or app running stage

FROM node:20-alpine
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY . .

EXPOSE 3000
CMD ["node","server.js"]

